name: Build Windows EXE

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install PyInstaller
        run: |
          python -m pip install --upgrade pip
          python -m pip install pyinstaller

      - name: Build EXE
        run: |
          pyinstaller --noconfirm --onefile --windowed --name Comparator --icon app_icon.ico comparator_app.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Comparator-Windows
          path: dist/Comparator.exe
